/*
startrail-service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the HelloWorldResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &HelloWorldResponse{}

// HelloWorldResponse struct for HelloWorldResponse
type HelloWorldResponse struct {
	Diagnostics []Diagnostic `json:"diagnostics"`
	Response NullableHelloWorld `json:"response,omitempty"`
	Success bool `json:"success"`
}

type _HelloWorldResponse HelloWorldResponse

// NewHelloWorldResponse instantiates a new HelloWorldResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHelloWorldResponse(diagnostics []Diagnostic, success bool) *HelloWorldResponse {
	this := HelloWorldResponse{}
	this.Diagnostics = diagnostics
	this.Success = success
	return &this
}

// NewHelloWorldResponseWithDefaults instantiates a new HelloWorldResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHelloWorldResponseWithDefaults() *HelloWorldResponse {
	this := HelloWorldResponse{}
	return &this
}

// GetDiagnostics returns the Diagnostics field value
func (o *HelloWorldResponse) GetDiagnostics() []Diagnostic {
	if o == nil {
		var ret []Diagnostic
		return ret
	}

	return o.Diagnostics
}

// GetDiagnosticsOk returns a tuple with the Diagnostics field value
// and a boolean to check if the value has been set.
func (o *HelloWorldResponse) GetDiagnosticsOk() ([]Diagnostic, bool) {
	if o == nil {
		return nil, false
	}
	return o.Diagnostics, true
}

// SetDiagnostics sets field value
func (o *HelloWorldResponse) SetDiagnostics(v []Diagnostic) {
	o.Diagnostics = v
}

// GetResponse returns the Response field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *HelloWorldResponse) GetResponse() HelloWorld {
	if o == nil || IsNil(o.Response.Get()) {
		var ret HelloWorld
		return ret
	}
	return *o.Response.Get()
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *HelloWorldResponse) GetResponseOk() (*HelloWorld, bool) {
	if o == nil {
		return nil, false
	}
	return o.Response.Get(), o.Response.IsSet()
}

// HasResponse returns a boolean if a field has been set.
func (o *HelloWorldResponse) HasResponse() bool {
	if o != nil && o.Response.IsSet() {
		return true
	}

	return false
}

// SetResponse gets a reference to the given NullableHelloWorld and assigns it to the Response field.
func (o *HelloWorldResponse) SetResponse(v HelloWorld) {
	o.Response.Set(&v)
}
// SetResponseNil sets the value for Response to be an explicit nil
func (o *HelloWorldResponse) SetResponseNil() {
	o.Response.Set(nil)
}

// UnsetResponse ensures that no value is present for Response, not even an explicit nil
func (o *HelloWorldResponse) UnsetResponse() {
	o.Response.Unset()
}

// GetSuccess returns the Success field value
func (o *HelloWorldResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *HelloWorldResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *HelloWorldResponse) SetSuccess(v bool) {
	o.Success = v
}

func (o HelloWorldResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o HelloWorldResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["diagnostics"] = o.Diagnostics
	if o.Response.IsSet() {
		toSerialize["response"] = o.Response.Get()
	}
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

func (o *HelloWorldResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"diagnostics",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varHelloWorldResponse := _HelloWorldResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varHelloWorldResponse)

	if err != nil {
		return err
	}

	*o = HelloWorldResponse(varHelloWorldResponse)

	return err
}

type NullableHelloWorldResponse struct {
	value *HelloWorldResponse
	isSet bool
}

func (v NullableHelloWorldResponse) Get() *HelloWorldResponse {
	return v.value
}

func (v *NullableHelloWorldResponse) Set(val *HelloWorldResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableHelloWorldResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableHelloWorldResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHelloWorldResponse(val *HelloWorldResponse) *NullableHelloWorldResponse {
	return &NullableHelloWorldResponse{value: val, isSet: true}
}

func (v NullableHelloWorldResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHelloWorldResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


