/*
startrail-service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StringResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StringResponse{}

// StringResponse struct for StringResponse
type StringResponse struct {
	Diagnostics []Diagnostic `json:"diagnostics"`
	Response NullableString `json:"response,omitempty"`
	Success bool `json:"success"`
}

type _StringResponse StringResponse

// NewStringResponse instantiates a new StringResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStringResponse(diagnostics []Diagnostic, success bool) *StringResponse {
	this := StringResponse{}
	this.Diagnostics = diagnostics
	this.Success = success
	return &this
}

// NewStringResponseWithDefaults instantiates a new StringResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStringResponseWithDefaults() *StringResponse {
	this := StringResponse{}
	return &this
}

// GetDiagnostics returns the Diagnostics field value
func (o *StringResponse) GetDiagnostics() []Diagnostic {
	if o == nil {
		var ret []Diagnostic
		return ret
	}

	return o.Diagnostics
}

// GetDiagnosticsOk returns a tuple with the Diagnostics field value
// and a boolean to check if the value has been set.
func (o *StringResponse) GetDiagnosticsOk() ([]Diagnostic, bool) {
	if o == nil {
		return nil, false
	}
	return o.Diagnostics, true
}

// SetDiagnostics sets field value
func (o *StringResponse) SetDiagnostics(v []Diagnostic) {
	o.Diagnostics = v
}

// GetResponse returns the Response field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StringResponse) GetResponse() string {
	if o == nil || IsNil(o.Response.Get()) {
		var ret string
		return ret
	}
	return *o.Response.Get()
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StringResponse) GetResponseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Response.Get(), o.Response.IsSet()
}

// HasResponse returns a boolean if a field has been set.
func (o *StringResponse) HasResponse() bool {
	if o != nil && o.Response.IsSet() {
		return true
	}

	return false
}

// SetResponse gets a reference to the given NullableString and assigns it to the Response field.
func (o *StringResponse) SetResponse(v string) {
	o.Response.Set(&v)
}
// SetResponseNil sets the value for Response to be an explicit nil
func (o *StringResponse) SetResponseNil() {
	o.Response.Set(nil)
}

// UnsetResponse ensures that no value is present for Response, not even an explicit nil
func (o *StringResponse) UnsetResponse() {
	o.Response.Unset()
}

// GetSuccess returns the Success field value
func (o *StringResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *StringResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *StringResponse) SetSuccess(v bool) {
	o.Success = v
}

func (o StringResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StringResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["diagnostics"] = o.Diagnostics
	if o.Response.IsSet() {
		toSerialize["response"] = o.Response.Get()
	}
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

func (o *StringResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"diagnostics",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStringResponse := _StringResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStringResponse)

	if err != nil {
		return err
	}

	*o = StringResponse(varStringResponse)

	return err
}

type NullableStringResponse struct {
	value *StringResponse
	isSet bool
}

func (v NullableStringResponse) Get() *StringResponse {
	return v.value
}

func (v *NullableStringResponse) Set(val *StringResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStringResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStringResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStringResponse(val *StringResponse) *NullableStringResponse {
	return &NullableStringResponse{value: val, isSet: true}
}

func (v NullableStringResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStringResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


